#!/bin/bash

s="${1}"; frasa=""

for((i=0;$i<${#s};i++)); do
	variable=${s:$i:1}

	case $variable in
		a)
			res="а"
			;;
		b)
			res="б"
			;;
		c)
			if [ "${s:$(( i+1 )):1}" = "h" ]; then
				(( i++ ))
				res="ч"
			else
				res="ц"
			fi
			;;
		d)
			res="д"
			;;
		e)
			res="е"
			;;
		f)
			res="ф"
			;;
		g)
			res="г"
			;;
		h)
			res="х"
			;;
		i)
			res="и"
			;;
		j)
			res="й"
			;;
		k)
			res="к"
			;;
		l)
			res="л"
			;;
		m)
			res="м"
			;;
		n)
			res="н"
			;;
		o)
			res="о"
			;;
		p)
			res="п"
			;;
		q)
			res="ку"
			;;
		r)
			res="р"
			;;
		s)
			a="${s:$(( i+1 )):1}"
			b="${s:$(( i+2 )):1}"
			if [ "${a}" = "h" ]; then
				(( i++ ))
				res="ш"
			elif [[ "${a}" = "c" && "${b}" = "h" ]]; then
				(( i+=2 ))
				res="щ"
			else
				res="с"
			fi
			;;
		t)
			res="т"
			;;
		u)
			res="у"
			;;
		v)
			res="в"
			;;
		w)
			res="в"
			;;
		x)
			res="кс"
			;;
		y)
			if [ "${s:$(( i+1 )):1}" = "u" ]; then
				(( i++ ))
				res="ю"
			elif [ "${s:$(( i+1 )):1}" = "a" ]; then
				(( i++ ))
				res="я"
			else
				u=$((${#frasa}-1))
				a=${frasa:$u:1}
				# после соглысных символ "y" обычно имеет нотацию "ы", а после гласных "й"
				case ${a} in
					"б"|"в"|"г"|"д"|"ж"|"з"|"к"|"л"|"м"|"н"|"п"|"р"|"с"|"т"|"ф"|"х"|"ц"|"ч"|"ш"|"щ")
						res="ы"
						;;
					*)
						res="й"
						;;
				esac
			fi
			;;
		z)
			if [ "${s:$(( i+1 )):1}" = "h" ]; then
				(( i++ ))
				res="ж"
			else
				res="з"
			fi
			;;
		-)
			res="_"
			;;
		*)
			res=${variable}
			;;
	esac
	frasa="${frasa}${res}"
done

echo "${frasa}"
